behaviors:
  AircraftLearning:
    trainer_type: ppo
    max_steps: 5.0e7
    time_horizon: 128
    summary_freq: 10000
    hyperparameters:
      batch_size: 2048
      beta: 1.0e-2
      buffer_size: 20480
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      num_epoch: 3
    network_settings:
      hidden_units: 256
      normalize: false
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
environment_parameters:
  checkpoint_radius:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: "reward"
          behavior: AircraftLearning
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 50.0
      - name: Lesson1
        completion_criteria:
          measure: "reward"
          behavior: AircraftLearning
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 30.0
      - name: Lesson2
        completion_criteria:
          measure: "reward"
          behavior: AircraftLearning
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4.0
        value: 20.0
      - name: Lesson3
        completion_criteria:
          measure: "reward"
          behavior: AircraftLearning
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6.0
        value: 10.0    
      - name: Lesson4
        value: 0.0          
