AircraftLearning:
    measure: "reward"    
    min_lesson_length: 100
    signal_smoothing: true
    thresholds: [ 2.0, 2.0, 4.0, 6.0 ]
    parameters:
        checkpoint_radius: [ 50.0, 30.0, 20.0, 10.0, 0.0 ]